# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66c0e32318b1f011668aefd0eed70b22cc53387f2ee3d0aa06b86e4da7fc6c3075cf8c25446023b73f2bb4f12f9846ed9d8939955a24915c3f20a02a1e4b9914

test:
  secret_key_base: 80a35cfb5df0c1c2d57df5d18343cecc8307c141bf8fe3f26bc7c28d5ce97e587e42f908f7320008ba3d40b3e562571cf56a40bb4c5d05a20cf8bb85769a1ef8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
